version: '3'
services:
    rproxy:
        build: ./rproxy
        hostname: rproxy_app
        network_mode: "host"
    # It's for master
    haproxy:
        build: ./haproxy
        dockerfile: Dockerfile_lb01
        hostname: haproxy_app
        network_mode: "host"
    # It's for slave
    #haproxy:
    #    build: ./haproxy
    #    dockerfile: Dockerfile_lb02
    #    hostname: haproxy_app
    #    network_mode: "host"
